#!/bin/sh
## Script called up strongswan to bring the vti interface up/down based on the state of the IPSec tunnel.
## Called as vti_up_down vti_intf_name

source /etc/default/vyatta
source /etc/default/locale
case "$PLUTO_VERB" in
route-client | up-client)
/opt/vyatta/sbin/vyatta-vti-config.pl --updown --intf=$1 --action=up
sysctl -w net.ipv4.conf.$1.disable_policy=1
sysctl -w net.ipv4.conf.$1.rp_filter=2 || sysctl -w net.ipv4.conf.$1.rp_filter=0
sudo /sbin/ip link set $1 up
sudo /sbin/iptables -t mangle -I FORWARD -o $1 -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
sudo /sbin/iptables -t mangle -I INPUT -p esp -s ${PLUTO_PEER} -d ${PLUTO_ME} -j MARK --set-xmark ${PLUTO_MARK_IN}
sudo /sbin/ip route flush table 220
    ;;
down-client)
/opt/vyatta/sbin/vyatta-vti-config.pl --updown --intf=$1 --action=down 
sudo /sbin/iptables -t mangle -D FORWARD -o $1 -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
sudo /sbin/iptables -t mangle -D INPUT -p esp -s ${PLUTO_PEER} -d ${PLUTO_ME} -j MARK --set-xmark ${PLUTO_MARK_IN}
    ;;
*)
    ;;
esac

sysctl -w net.ipv4.ip_forward=1
sysctl -w net.ipv4.conf.lo.disable_xfrm=1
sysctl -w net.ipv4.conf.lo.disable_policy=1
sysctl -w net.ipv4.conf.eth0.disable_xfrm=1
sysctl -w net.ipv4.conf.eth0.disable_policy=1
sysctl -w net.ipv4.conf.eth1.disable_xfrm=1
sysctl -w net.ipv4.conf.eth1.disable_policy=1
sysctl -w net.ipv4.conf.eth2.disable_xfrm=1
sysctl -w net.ipv4.conf.eth2.disable_policy=1
sysctl -w net.ipv4.conf.eth3.disable_xfrm=1
sysctl -w net.ipv4.conf.eth3.disable_policy=1
sysctl -w net.ipv4.conf.eth4.disable_xfrm=1
sysctl -w net.ipv4.conf.eth4.disable_policy=1
sysctl -w net.ipv4.conf.eth5.disable_xfrm=1
sysctl -w net.ipv4.conf.eth5.disable_policy=1
exit 0



